name: test

on: [push, pull_request]

jobs:
  build:
    name: Rust ${{ matrix.os }} ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
          token: ${{ secrets.ACTIONS_TOKEN }}
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Build for OS X
      if: matrix.os == 'macos-latest'
      run: |
          brew install cmake
          brew install libomp
          cargo build
    - name: Build for ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt-get update
          sudo apt-get install -y cmake libclang-dev libc++-dev gcc-multilib
          cargo build
    - name: Run tests
      run: cargo test
      continue-on-error: ${{ matrix.rust == 'nightly' }}
